const MyProjects = [
  {
    id: 1,
    urlimage: '../project-1.png',
    typeProject: 'website',
    title: 'RentUp',
    desc: "RentUP is a modern and user-centric real estate website designed to help users find their next home with ease. Whether you're searching for a family house, an apartment, or a luxury villa, RentUP provides a seamless and intuitive experience tailored to meet the diverse needs of property seekers.",
    basicLanguages: ['#html', '#css'],
    frameworks: '',
    libraries: '',
    github: '',
  },
  {
    id: 2,
    urlimage: '../project-2.png',
    typeProject: 'website',
    title: 'K2skiing',
    desc: 'K2skiing is a dynamic and visually engaging website designed for ski enthusiasts and adventurers seeking the best skiing and snowboarding experiences. The site is tailored to offer a comprehensive range of activities, guides, and resources to help users plan and enjoy their skiing trips.',
    basicLanguages: ['#html', '#css'],
    // basicLanguages: {
    //   0: 'HTML',
    //   1: 'CSS',
    //   2: 'JavaScript',
    // },
    frameworks: '',
    libraries: '',
    github: '',
  },
  {
    id: 3,
    urlimage: '../project-3.png',
    typeProject: 'website',
    title: 'B-World',
    desc: 'B-world is an innovative and user-centric online platform designed for book lovers and literary enthusiasts. The website is thoughtfully crafted to provide a seamless and visually appealing experience, where users can discover, explore, and connect with a wide range of books.',
    basicLanguages: ['#html', '#css', '#javaScript'],
    frameworks: '#Tailwind CSS',
    libraries: '#React',
    github: 'https://github.com/mohammed-ismaeel/Task5_Books',
  },
  {
    id: 4,
    urlimage: '../project-4.png',
    typeProject: 'website',
    title: 'Furniture',
    desc: 'Furniture is a sleek and innovative website designed to provide users with the best shopping experience for furniture and home decor. The site features a modern and minimalist design, making it easy for users to discover the latest collections and purchase items that add a touch of elegance to their homes.',
    basicLanguages: ['#html', '#css', '#javaScript'],
    frameworks: '',
    libraries: '',

    github: '',
  },
  {
    id: 5,
    urlimage: '../project-5.png',
    typeProject: 'website',
    title: 'Organick',
    desc: 'Organick is a clean and vibrant website designed for health-conscious consumers seeking organic products. The site offers a range of fresh fruits, vegetables, nuts, and health foods, with promotions on select items. Optimized for all devices, it provides an easy shopping experience with a focus on eco-friendly practices and high-quality standards.',
    basicLanguages: ['#html', '#css', '#javaScript'],
    frameworks: '',
    libraries: '',
    github: '',
  },
  {
    id: 6,
    urlimage: '../project-6.png',
    typeProject: 'website',
    title: 'Travel Agency',
    desc: 'Travel is a visually engaging website designed for travelers seeking exceptional tour packages. It offers services like guided tours, flights, and medical insurance, featuring top destinations such as Switzerland, the Amazon, and Giza. The site is optimized for all devices, providing a seamless booking experience.',
    basicLanguages: ['#html', '#css', '#javaScript'],
    frameworks: '',
    libraries: '#React',
    github: '',
  },
  // {
  //   id: 7,
  //   urlimage: '../project-7.png',
  //   typeProject: 'website',
  //   title: 'AI Blog',
  //   desc: 'AI Blog & AI News is a platform featuring AI-generated content on the latest developments in artificial intelligence. Covering topics like AI in e-commerce, ethics, legal issues, and technology trends, it provides informative and engaging articles with minimal human intervention.',
  //   tools: 'HTML&CSS . JavaScript',
  //   Frameworks: 'Laravel',
  //   Libraries: 'React',
  //   github: '',
  // },
]

export default MyProjects
